# Generated by Django 4.0.6 on 2022-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('birth', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
