# Generated by Django 4.0.6 on 2022-08-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_musicvideo_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='rating_id',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='user_id',
        ),
    ]
