# Generated by Django 4.0.6 on 2022-08-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_rating_id_rating_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicvideo',
            old_name='rateScore',
            new_name='rate_score',
        ),
        migrations.RenameField(
            model_name='musicvideo',
            old_name='votesNumber',
            new_name='votes_number',
        ),
        migrations.RenameField(
            model_name='musicvideo',
            old_name='ytEmbedded',
            new_name='yt_embedded',
        ),
    ]
