# Generated by Django 4.0.6 on 2022-08-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_ratescore_musicvideo_rate_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
