# Generated by Django 4.0.6 on 2022-08-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_musicvideo_genre_alter_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideolist',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='genre',
            field=models.CharField(choices=[('none', 'None'), ('pop', 'Pop'), ('rock', 'Rock'), ('poprock', 'Pop-Rock'), ('electronic', 'Electronic'), ('synth-pop', 'Synth-Pop'), ('heavymetal', 'Heavy-Metal')], default=None, max_length=50),
        ),
    ]
