# Generated by Django 4.0.6 on 2022-08-19 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_musicvideo_content_type_alter_musicvideo_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicvideo',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist'),
        ),
    ]
