# Generated by Django 4.0.6 on 2022-08-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_musicvideo_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='song_description',
            field=models.CharField(default='No info', max_length=255),
        ),
    ]
