# Generated by Django 4.0.6 on 2022-08-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_musicvideo_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(choices=[('artist', 'artist'), ('band', 'band')], default=('artist', 'artist'), max_length=10),
        ),
    ]
