# Generated by Django 4.0.6 on 2022-08-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_artist_type_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='rate_score',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='votes_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
