# Generated by Django 4.0.6 on 2022-09-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_musicvideo_rate_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='type',
            field=models.CharField(choices=[('none', 'None'), ('artist', 'artist'), ('band', 'band')], max_length=10),
        ),
    ]
