# Generated by Django 4.0.6 on 2022-09-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_artist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='genre',
            field=models.CharField(choices=[('none', 'None'), ('pop', 'Pop'), ('rock', 'Rock'), ('pop-rock', 'Pop-Rock'), ('electronic', 'Electronic'), ('synth-pop', 'Synth-Pop'), ('heavymetal', 'Heavy-Metal')], default=None, max_length=50, null=True),
        ),
    ]
