# Generated by Django 4.0.6 on 2022-09-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_artist_description_alter_artist_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=1200),
        ),
    ]
