# Generated by Django 4.0.6 on 2022-09-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
